// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"Prove/webook/interactive/events"
	"Prove/webook/interactive/grpc"
	"Prove/webook/interactive/ioc"
	"Prove/webook/interactive/repository"
	"Prove/webook/interactive/repository/cache"
	"Prove/webook/interactive/repository/dao"
	"Prove/webook/interactive/service"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitApp() *App {
	cmdable := ioc.InitRedis()
	interactiveCache := cache.NewRedisInteractiveCache(cmdable)
	loggerV1 := ioc.InitLogger()
	srcDB := ioc.InitSRC(loggerV1)
	dstDB := ioc.InitDST(loggerV1)
	db := ioc.InitBizDB(loggerV1, srcDB, dstDB)
	interactiveDAO := dao.NewGORMInteractiveDAO(db)
	interactiveRepository := repository.NewCachedInteractiveRepository(interactiveCache, interactiveDAO, loggerV1)
	interactiveService := service.NewInteractiveService(interactiveRepository, loggerV1)
	interactiveServiceServer := grpc.NewInteractiveServiceServer(interactiveService)
	client := ioc.InitEtcdClient()
	server := ioc.InitGRPCxServer(interactiveServiceServer, client, loggerV1)
	saramaClient := ioc.InitKafka()
	interactiveReadEventConsumer := events.NewInteractiveReadEventConsumer(saramaClient, loggerV1, interactiveRepository)
	consumer := ioc.InitFixDataConsumer(loggerV1, srcDB, dstDB, saramaClient)
	v := ioc.NewConsumers(interactiveReadEventConsumer, consumer)
	doubleWritePool := ioc.InitDoubleWritePool(srcDB, dstDB, loggerV1)
	syncProducer := ioc.InitSyncProducer(saramaClient)
	producer := ioc.InitMigradatorProducer(syncProducer)
	ginxServer := ioc.InitMigratorWeb(loggerV1, srcDB, dstDB, doubleWritePool, producer)
	app := &App{
		server:    server,
		consumers: v,
		webAdmin:  ginxServer,
	}
	return app
}

// wire.go:

var thirdProvider = wire.NewSet(ioc.InitSRC, ioc.InitDST, ioc.InitDoubleWritePool, ioc.InitBizDB, ioc.InitRedis, ioc.InitLogger, ioc.InitKafka, ioc.InitSyncProducer, ioc.InitEtcdClient)

var interactiveSvcProvider = wire.NewSet(dao.NewGORMInteractiveDAO, cache.NewRedisInteractiveCache, repository.NewCachedInteractiveRepository, service.NewInteractiveService)

var migratorProvider = wire.NewSet(ioc.InitMigratorWeb, ioc.InitMigradatorProducer, ioc.InitFixDataConsumer)
