version: "3"
services:

  mysql8:
    image: mysql:8.0.25
    command: --default_authentication_plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      # 设置初始化脚本
#      - ./script/mysql/user.sql:docker-entrypoint-initdb.d
      - D:\go\GO-LEARNING\src\Prove\webook\script\mysql:/docker-entrypoint-initdb.d
    ports:
      # 映射 13316端口
      - "13316:3306"

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"

  etcd:
    image: 'bitnami/etcd:latest'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    ports:
      - "12379:2379"

  mongo:
    image: mongo:6.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"

#  mongo-express:
#    image: mongo-express:0.54
#    restart: always
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: example
#      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
#    ports:
#      - "18081:8081"