apiVersion: v1
kind: Service
metadata:
  name: webook-mysql
spec:
  selector:
    app: webook-mysql
  ports:
    - protocol: TCP
#     service本身
      port: 3308
#     Pod 上暴露的端口
      targetPort: 3306
#     集群外访问的端口
      nodePort: 30002
  type: NodePort
