// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	article3 "Prove/webook/internal/events/article"
	"Prove/webook/internal/repository"
	article2 "Prove/webook/internal/repository/article"
	"Prove/webook/internal/repository/cache"
	"Prove/webook/internal/repository/dao"
	"Prove/webook/internal/repository/dao/article"
	"Prove/webook/internal/service"
	"Prove/webook/internal/web"
	"Prove/webook/internal/web/jwt"
	"Prove/webook/ioc"
	"github.com/google/wire"
)

import (
	_ "github.com/gin-contrib/sessions/redis"
	_ "github.com/spf13/viper/remote"
)

// Injectors from wire.go:

func InitWebServer() *App {
	cmdable := ioc.InitRedis()
	loggerV1 := ioc.InitLogger()
	handler := jwt.NewRedisJWT(cmdable)
	v := ioc.InitMiddlewares(cmdable, loggerV1, handler)
	db := ioc.InitDB(loggerV1)
	userDAO := dao.NewUserInfoDAO(db)
	userCache := cache.NewUserCache(cmdable)
	userRepository := repository.NewUserInfoRepository(userDAO, userCache)
	userAndService := service.NewUserService(userRepository, loggerV1)
	codeCache := cache.NewRedisCodeCache(cmdable)
	codeRepository := repository.NewCodeRepository(codeCache)
	smsService := ioc.InitSMSService(cmdable)
	codeAndService := service.NewCodeService(codeRepository, smsService)
	userHandler := web.NewUserHandler(userAndService, codeAndService, handler, loggerV1)
	wechatService := ioc.InitWechatService(loggerV1)
	wechatHandlerConfig := ioc.InitWechatHandlerConfig()
	oAuth2WechatHandler := web.NewOAuth2WechatHandler(wechatService, userAndService, wechatHandlerConfig, handler)
	articleDAO := article.NewGORMArticleDAO(db)
	articleRepository := article2.NewArticleRepository(articleDAO, loggerV1)
	client := ioc.InitKafka()
	syncProducer := ioc.NewSyncProducer(client)
	producer := article3.NewKafkaProducer(syncProducer)
	articleService := service.NewArticleService(articleRepository, loggerV1, producer)
	articleHandler := web.NewArticleHandler(articleService, loggerV1)
	engine := ioc.InitEngine(v, userHandler, oAuth2WechatHandler, articleHandler)
	interactiveCache := cache.NewRedisInteractiveCache(cmdable)
	interactiveDAO := dao.NewGORMInteractiveDAO(db)
	interactiveRepository := repository.NewCachedInteractiveRepository(interactiveCache, interactiveDAO, loggerV1)
	interactiveReadEventConsumer := article3.NewInteractiveReadEventBatchConsumer(client, loggerV1, interactiveRepository)
	v2 := ioc.NewConsumers(interactiveReadEventConsumer)
	interactiveService := service.NewInteractiveService(interactiveRepository, loggerV1)
	rankingService := service.NewBatchRankingService(articleService, interactiveService)
	rlockClient := ioc.InitRLockClient(cmdable)
	rankingJob := ioc.InitRankingJob(rankingService, loggerV1, rlockClient)
	cron := ioc.InitJobs(loggerV1, rankingJob)
	app := &App{
		server:    engine,
		consumers: v2,
		cron:      cron,
	}
	return app
}

// wire.go:

var (
	// 第三方依赖
	thirdProvider = wire.NewSet(ioc.InitDB, ioc.InitRedis, ioc.InitRLockClient, ioc.InitLogger, ioc.InitKafka, ioc.NewConsumers, ioc.NewSyncProducer)

	// 用户模块
	userProvider = wire.NewSet(dao.NewUserInfoDAO, cache.NewUserCache, repository.NewUserInfoRepository, service.NewUserService)

	// 验证码模块
	codeProvider = wire.NewSet(cache.NewRedisCodeCache, repository.NewCodeRepository, service.NewCodeService)

	// 文章模块
	articleProvider = wire.NewSet(article.NewGORMArticleDAO, article2.NewArticleRepository, service.NewArticleService)

	// 阅读计数模块
	interProvider = wire.NewSet(dao.NewGORMInteractiveDAO, cache.NewRedisInteractiveCache, repository.NewCachedInteractiveRepository, service.NewInteractiveService)

	// 排行榜模块
	rankingProvider = wire.NewSet(cache.NewRankingRedisCache, repository.NewCachedRankingRepository, service.NewBatchRankingService)
)
