// Code generated by MockGen. DO NOT EDIT.
// Source: webook\internal\service\code.go

// Package svcmocks is a generated GoMock package.
package svcmocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCodeAndService is a mock of CodeAndService interface.
type MockCodeAndService struct {
	ctrl     *gomock.Controller
	recorder *MockCodeAndServiceMockRecorder
}

// MockCodeAndServiceMockRecorder is the mock recorder for MockCodeAndService.
type MockCodeAndServiceMockRecorder struct {
	mock *MockCodeAndService
}

// NewMockCodeAndService creates a new mock instance.
func NewMockCodeAndService(ctrl *gomock.Controller) *MockCodeAndService {
	mock := &MockCodeAndService{ctrl: ctrl}
	mock.recorder = &MockCodeAndServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCodeAndService) EXPECT() *MockCodeAndServiceMockRecorder {
	return m.recorder
}

// Send mocks base method.
func (m *MockCodeAndService) Send(ctx context.Context, biz, phone string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, biz, phone)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockCodeAndServiceMockRecorder) Send(ctx, biz, phone interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockCodeAndService)(nil).Send), ctx, biz, phone)
}

// Verify mocks base method.
func (m *MockCodeAndService) Verify(ctx context.Context, biz, phone, inputCode string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Verify", ctx, biz, phone, inputCode)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Verify indicates an expected call of Verify.
func (mr *MockCodeAndServiceMockRecorder) Verify(ctx, biz, phone, inputCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Verify", reflect.TypeOf((*MockCodeAndService)(nil).Verify), ctx, biz, phone, inputCode)
}
