// Code generated by MockGen. DO NOT EDIT.
// Source: webook\internal\service\user.go
//
// Generated by this command:
//
//	mockgen -source=webook\internal\service\user.go -destination=webook\internal\service\mocks\user.mock.go -package=svcmocks
//
// Package svcmocks is a generated GoMock package.
package svcmocks

import (
	domain "Prove/webook/internal/domain"
	context "context"
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "go.uber.org/mock/gomock"
)

// MockUserAndService is a mock of UserAndService interface.
type MockUserAndService struct {
	ctrl     *gomock.Controller
	recorder *MockUserAndServiceMockRecorder
}

// MockUserAndServiceMockRecorder is the mock recorder for MockUserAndService.
type MockUserAndServiceMockRecorder struct {
	mock *MockUserAndService
}

// NewMockUserAndService creates a new mock instance.
func NewMockUserAndService(ctrl *gomock.Controller) *MockUserAndService {
	mock := &MockUserAndService{ctrl: ctrl}
	mock.recorder = &MockUserAndServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserAndService) EXPECT() *MockUserAndServiceMockRecorder {
	return m.recorder
}

// Edit mocks base method.
func (m *MockUserAndService) Edit(ctx context.Context, u *domain.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Edit", ctx, u)
	ret0, _ := ret[0].(error)
	return ret0
}

// Edit indicates an expected call of Edit.
func (mr *MockUserAndServiceMockRecorder) Edit(ctx, u any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Edit", reflect.TypeOf((*MockUserAndService)(nil).Edit), ctx, u)
}

// FindOrCreate mocks base method.
func (m *MockUserAndService) FindOrCreate(ctx context.Context, phone string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOrCreate", ctx, phone)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOrCreate indicates an expected call of FindOrCreate.
func (mr *MockUserAndServiceMockRecorder) FindOrCreate(ctx, phone any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOrCreate", reflect.TypeOf((*MockUserAndService)(nil).FindOrCreate), ctx, phone)
}

// FindOrCreateByWechat mocks base method.
func (m *MockUserAndService) FindOrCreateByWechat(ctx *gin.Context, wechatInfo domain.WechatInfo) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOrCreateByWechat", ctx, wechatInfo)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOrCreateByWechat indicates an expected call of FindOrCreateByWechat.
func (mr *MockUserAndServiceMockRecorder) FindOrCreateByWechat(ctx, wechatInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOrCreateByWechat", reflect.TypeOf((*MockUserAndService)(nil).FindOrCreateByWechat), ctx, wechatInfo)
}

// Login mocks base method.
func (m *MockUserAndService) Login(ctx context.Context, email, password string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, email, password)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockUserAndServiceMockRecorder) Login(ctx, email, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockUserAndService)(nil).Login), ctx, email, password)
}

// Profile mocks base method.
func (m *MockUserAndService) Profile(ctx context.Context, id int64) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Profile", ctx, id)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Profile indicates an expected call of Profile.
func (mr *MockUserAndServiceMockRecorder) Profile(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Profile", reflect.TypeOf((*MockUserAndService)(nil).Profile), ctx, id)
}

// Signup mocks base method.
func (m *MockUserAndService) Signup(ctx context.Context, u *domain.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Signup", ctx, u)
	ret0, _ := ret[0].(error)
	return ret0
}

// Signup indicates an expected call of Signup.
func (mr *MockUserAndServiceMockRecorder) Signup(ctx, u any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signup", reflect.TypeOf((*MockUserAndService)(nil).Signup), ctx, u)
}
