db:
  src:
    dsn: "root:root@tcp(localhost:13316)/webook"
  dst:
    dsn: "root:root@tcp(localhost:13316)/webook_inter"

migrator:
  pattern: "SRC_ONLY"
  web:
    addr: ":8082"

redis:
  addr: "localhost:6379"

kafka:
  addrs:
    - "localhost:9094"

etcd:
  endpoints:
    - "localhost:12379"
grpc:
  server:
    #  启动监听 8094 端口
    port: 8094
    etcdAddr: "localhost:12379"
    etcdTTL: 60