// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"Prove/wire/repository"
	"Prove/wire/repository/dao"
)

// Injectors from wire.go:

func InitRepository() *repository.UserInfoRepository {
	db := InitDB()
	userInfoDAO := dao.NewUserInfoDAO(db)
	userInfoRepository := repository.NewUserInfoRepository(userInfoDAO)
	return userInfoRepository
}
