### 查看创作者文章
GET http://localhost:8080/articles/13357
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDIxMDA2MTQsIlVzZXJJZCI6NywiU3NpZCI6ImNiZjI1YWU2LTM0MDUtNGM2MS05MWM2LTQ0NDg0ZDhhOGY0YyIsIlVzZXJBZ2VudCI6IkFwYWNoZS1IdHRwQ2xpZW50LzQuNS4xMyAoSmF2YS8xNy4wLjMpIn0.98HAV_-uswxnFiA9j1JfzXUCTnvL9r2pq0D1rmCe-wn25Ks1eR97PzPdtAr4MoQPWhI9gMc-As0Z7EXUAs7epA

### 编辑文章
POST http://localhost:8080/articles/edit
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDIxMDI0NDksIlVzZXJJZCI6NywiU3NpZCI6ImRhMDJlNTU1LTMwZTctNDRhYS04NzVmLTlkZDQ1MDYxMDIwMyIsIlVzZXJBZ2VudCI6IkFwYWNoZS1IdHRwQ2xpZW50LzQuNS4xMyAoSmF2YS8xNy4wLjMpIn0.yeNEsaDCBIHuE-XQQIL2h4yg8Cv79rY_Q_35utU7k6h7DutGe_B81MsOvTgqSvv8wn-eOJ4QJyE-oo-nQGWQKg

{
  "title":"思念456789",
  "content": "举头，思乡"
}

### 上传文章
POST http://localhost:8080/articles/publish
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDIxMDI0NDksIlVzZXJJZCI6NywiU3NpZCI6ImRhMDJlNTU1LTMwZTctNDRhYS04NzVmLTlkZDQ1MDYxMDIwMyIsIlVzZXJBZ2VudCI6IkFwYWNoZS1IdHRwQ2xpZW50LzQuNS4xMyAoSmF2YS8xNy4wLjMpIn0.yeNEsaDCBIHuE-XQQIL2h4yg8Cv79rY_Q_35utU7k6h7DutGe_B81MsOvTgqSvv8wn-eOJ4QJyE-oo-nQGWQKg

{
  "id" :13,
  "title":"思念456789",
  "content": "举头，思乡"
}

### 撤回文章
POST http://localhost:8080/articles/publish
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDIxMDI0NDksIlVzZXJJZCI6NywiU3NpZCI6ImRhMDJlNTU1LTMwZTctNDRhYS04NzVmLTlkZDQ1MDYxMDIwMyIsIlVzZXJBZ2VudCI6IkFwYWNoZS1IdHRwQ2xpZW50LzQuNS4xMyAoSmF2YS8xNy4wLjMpIn0.yeNEsaDCBIHuE-XQQIL2h4yg8Cv79rY_Q_35utU7k6h7DutGe_B81MsOvTgqSvv8wn-eOJ4QJyE-oo-nQGWQKg

{
  "id" :13
}

### 创作者查询所有文章
POST http://localhost:8080/articles/list
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDIxMDI0NDksIlVzZXJJZCI6NywiU3NpZCI6ImRhMDJlNTU1LTMwZTctNDRhYS04NzVmLTlkZDQ1MDYxMDIwMyIsIlVzZXJBZ2VudCI6IkFwYWNoZS1IdHRwQ2xpZW50LzQuNS4xMyAoSmF2YS8xNy4wLjMpIn0.yeNEsaDCBIHuE-XQQIL2h4yg8Cv79rY_Q_35utU7k6h7DutGe_B81MsOvTgqSvv8wn-eOJ4QJyE-oo-nQGWQKg

{
  "id" :13
}